export const COMPONENT_TYPES = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  CONTAINER: "CONTAINER",
  BUTTON: "BUTTON",
  LOGIN: "LOGIN",
  BOARD: "BOARD",
  DETAIL_PAGE: "DETAIL_PAGE",
  ROW: "ROW",
  COLUMN: "COLUMN",
};

// COMPONENT_TYPES 문자열 상수 내보내기 - 타입 참조용
export const TEXT = COMPONENT_TYPES.TEXT;
export const IMAGE = COMPONENT_TYPES.IMAGE;
export const CONTAINER = COMPONENT_TYPES.CONTAINER;
export const BUTTON = COMPONENT_TYPES.BUTTON;
export const LOGIN = COMPONENT_TYPES.LOGIN;
export const BOARD = COMPONENT_TYPES.BOARD;
export const DETAIL_PAGE = COMPONENT_TYPES.DETAIL_PAGE;
export const ROW = COMPONENT_TYPES.ROW;
export const COLUMN = COMPONENT_TYPES.COLUMN;